<a href="https://colab.research.google.com/github/ashitasingh1230-commits/IT_support_ticket_analysis/blob/main/01_sla_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df=pd.read_csv('itsm_ticket_corpus_flat.csv')
df.head()

,record_id,record_type,ticket,status,correspondence,diagnostics,root_cause,resolution
0,INC-ALP-0001,incident,"{""submitted_at"": ""2025-11-18T08:00:00Z"", ""subm...",closed,"[{""turn_id"": 1, ""role"": ""agent"", ""event_type"":...","{""coverage"": ""standard"", ""summary"": ""Diagnosti...",Cached credentials on the user's iPhone contin...,"{""steps"": [""Reviewed Active Directory lockout ..."
1,INC-ALP-0002,incident,"{""submitted_at"": ""2025-11-18T13:48:00Z"", ""subm...",closed,"[{""turn_id"": 1, ""role"": ""agent"", ""event_type"":...","{""coverage"": ""standard"", ""summary"": ""Diagnosti...",Stale cached credentials on the user's iOS mob...,"{""steps"": [""Reviewed account lockout activity ..."
2,INC-ALP-0003,incident,"{""submitted_at"": ""2025-11-18T19:36:00Z"", ""subm...",closed,"[{""turn_id"": 1, ""role"": ""agent"", ""event_type"":...","{""coverage"": ""standard"", ""summary"": ""Diagnosti...",Active Directory lockout policy was triggered ...,"{""steps"": [""Reviewed the account status for md..."
3,INC-ALP-0004,incident,"{""submitted_at"": ""2025-11-19T01:24:00Z"", ""subm...",closed,"[{""turn_id"": 1, ""role"": ""agent"", ""event_type"":...","{""coverage"": ""standard"", ""summary"": ""Diagnosti...",The Active Directory lockout policy was trigge...,"{""steps"": [""Unlock the user's Active Directory..."
4,INC-ALP-0005,incident,"{""submitted_at"": ""2025-11-19T07:12:00Z"", ""subm...",closed,"[{""turn_id"": 1, ""role"": ""agent"", ""event_type"":...","{""coverage"": ""standard"", ""summary"": ""Diagnosti...",Active Directory lockout policy was triggered ...,"{""steps"": [""Reviewed Active Directory lockout ..."

In [2]:
df.columns

Index(['record_id', 'record_type', 'ticket', 'status', 'correspondence',
       'diagnostics', 'root_cause', 'resolution'],
      dtype='object')

In [3]:
df.shape

(745, 8)

In [4]:
df['record_type'].value_counts()

record_type
incident    745
Name: count, dtype: int64

In [6]:
df['status'].value_counts()

status
closed    745
Name: count, dtype: int64

In [7]:
df['root_cause'].value_counts()

root_cause
Likely mailbox-side Exchange Online synchronization fault or service condition affecting multiple clients for a single user, not caused by mobile device compliance or a simple stale local Outlook session.                                                                                                                                                                                                               1
Cached credentials on the user's iPhone continued submitting the old password after the reset, generating repeated failed authentications against Active Directory and triggering the account lockout policy before the new password could be used successfully in SSO.                                                                                                                                                    1
Stale cached credentials on the user's iOS mobile device continued submitting the old password to Active Directory and SSO-connected services after the self-service password reset, repeatedly triggering the AD lockout policy.                                                                                                                                                                                          1
Active Directory lockout policy was triggered by repeated failed sign-in attempts from the user's iOS mobile device, which continued using cached pre-reset credentials after the prior password reset token expired before the device updated its stored authentication data.                                                                                                                                             1
The Active Directory lockout policy was triggered by repeated authentication attempts from a mobile device using stale cached credentials. While the password reset request completed in the Password Reset Portal, the locked account state and delayed propagation of the new credential to the SSO path prevented successful sign-in until the lockout source was remediated and the account state was synchronized.    1
                                                                                                                                                                                                                                                                                                                                                                                                                          ..
Repeated AD lockouts were caused by stale cached credentials and saved authentication tokens on the user's company iPhone, which continued sending failed sign-in attempts to SSO/Active Directory after the initial unlock. The earlier remediation restored account access temporarily but did not remove the outdated mobile credentials, so the lockout condition recurred.                                            1
Active Directory lockout was repeatedly re-triggered by a mobile device using cached or expired corporate credentials. Although the user completed a password reset, the stale mobile authentication attempts continued to submit the old password and prevented the account from remaining unlocked long enough for normal sign-in.                                                                                       1
Active Directory domain lockout policy was triggered by repeated failed authentication attempts from a mobile device with stale cached credentials, preventing SSO access; the user's reset attempt did not complete recovery because the password reset token had already expired.                                                                                                                                        1
The AD account lockout policy was triggered by repeated failed authentication attempts from the user's corporate iPhone, which continued submitting cached old credentials after the password reset workflow began. In parallel, the original SSPR token expired before the reset was completed, delaying successful credential update and recovery.                                                                       1
Active Directory lockout policy was repeatedly triggered by stale cached credentials on the user's iOS mobile device, which continued to submit failed authentication attempts after the password reset.                                                                                                                                                                                                                   1
Name: count, Length: 745, dtype: int64

In [10]:
df['root_cause'].iloc[0]

"Cached credentials on the user's iPhone continued submitting the old password after the reset, generating repeated failed authentications against Active Directory and triggering the account lockout policy before the new password could be used successfully in SSO."

In [11]:
df['ticket'].iloc[0]

'{"submitted_at": "2025-11-18T08:00:00Z", "submitted_title": "AD account locked after password reset", "submitted_description": "I completed a corporate password reset through the Password Reset Portal on 2025-11-18 at approximately 07:45 UTC, but sign-in to the SSO Portal at https://sso.corplabs.com continued to fail with a locked-account error and my Active Directory account (username: mcarson) became locked again within minutes. I primarily authenticate from my iPhone (WORKSTATION-IPHONE-MC) at the Charlotte office, with previously saved credentials in the iOS Mail app and Safari browser, which prevented successful access to corporate resources including Outlook and SharePoint after the password change. My employee ID is EMP-20418 and I need access restored urgently for a client presentation this morning.", "priority": "high", "sla_plan": "Business-hours SLA", "environment": {"os": "iOS 15.6", "platform": "mobile", "region": "us-east-1", "user_group": "Corp Users"}, "applications": ["Password Reset Portal", "SSO Portal"]}'

In [12]:
import json

In [13]:
first_ticket=json.loads(df['ticket'].iloc[0])
first_ticket

{'submitted_at': '2025-11-18T08:00:00Z',
 'submitted_title': 'AD account locked after password reset',
 'submitted_description': 'I completed a corporate password reset through the Password Reset Portal on 2025-11-18 at approximately 07:45 UTC, but sign-in to the SSO Portal at https://sso.corplabs.com continued to fail with a locked-account error and my Active Directory account (username: mcarson) became locked again within minutes. I primarily authenticate from my iPhone (WORKSTATION-IPHONE-MC) at the Charlotte office, with previously saved credentials in the iOS Mail app and Safari browser, which prevented successful access to corporate resources including Outlook and SharePoint after the password change. My employee ID is EMP-20418 and I need access restored urgently for a client presentation this morning.',
 'priority': 'high',
 'sla_plan': 'Business-hours SLA',
 'environment': {'os': 'iOS 15.6',
  'platform': 'mobile',
  'region': 'us-east-1',
  'user_group': 'Corp Users'},
 'applications': ['Password Reset Portal', 'SSO Portal']}

In [14]:
first_ticket['priority']

'high'

In [15]:
print(first_ticket['submitted_title'])
print(first_ticket['sla_plan'])
print(first_ticket['environment'])

AD account locked after password reset
Business-hours SLA
{'os': 'iOS 15.6', 'platform': 'mobile', 'region': 'us-east-1', 'user_group': 'Corp Users'}

In [16]:
df['ticket_parsed']=df['ticket'].apply(json.loads)

In [17]:
df['ticket_parsed'].iloc[0]

{'submitted_at': '2025-11-18T08:00:00Z',
 'submitted_title': 'AD account locked after password reset',
 'submitted_description': 'I completed a corporate password reset through the Password Reset Portal on 2025-11-18 at approximately 07:45 UTC, but sign-in to the SSO Portal at https://sso.corplabs.com continued to fail with a locked-account error and my Active Directory account (username: mcarson) became locked again within minutes. I primarily authenticate from my iPhone (WORKSTATION-IPHONE-MC) at the Charlotte office, with previously saved credentials in the iOS Mail app and Safari browser, which prevented successful access to corporate resources including Outlook and SharePoint after the password change. My employee ID is EMP-20418 and I need access restored urgently for a client presentation this morning.',
 'priority': 'high',
 'sla_plan': 'Business-hours SLA',
 'environment': {'os': 'iOS 15.6',
  'platform': 'mobile',
  'region': 'us-east-1',
  'user_group': 'Corp Users'},
 'applications': ['Password Reset Portal', 'SSO Portal']}

In [18]:
df['priority']=df['ticket_parsed'].apply(lambda x : x['priority'])

In [19]:
df['priority'].value_counts()

priority
medium    254
high      249
low       242
Name: count, dtype: int64

In [20]:
df['sla_plan']=df['ticket_parsed'].apply(lambda x : x['sla_plan'])
df['sla_plan'].value_counts()

sla_plan
Standard Business Hours             99
Standard                            47
standard                            41
Gold                                30
Standard SLA                        17
                                    ..
Corporate SLA - Standard 8x5         1
Corporate-Network-SLA                1
Tier 2 Network - 4 hour response     1
Gold - 4 hours                       1
BusinessHours                        1
Name: count, Length: 281, dtype: int64

In [21]:
df['sla_plan_clean']=df['sla_plan'].str.lower().str.strip()
df['sla_plan_clean'].value_counts()

sla_plan_clean
standard business hours        99
standard                       88
gold                           31
standard sla                   17
standard business hours sla    15
                               ..
enterprise vpn sla              1
gold sla                        1
standard - 24x5 network sla     1
gold - 4 hours                  1
businesshours                   1
Name: count, Length: 274, dtype: int64

In [22]:
def catergorise_sla(text):
  if 'gold' in text:
    return 'Gold'
  elif 'standard' in text or 'businesshours' in text or 'business hours' in text:
    return 'Standard'
  else:
    return 'Others'
df['sla_category']=df['sla_plan_clean'].apply(catergorise_sla)
df['sla_category'].value_counts()

sla_category
Standard    598
Gold         78
Others       69
Name: count, dtype: int64

In [23]:
df[df['sla_category']=='Others']['sla_plan_clean'].unique()[:20]

array(['business-hours sla', 'enterprise sla', 'tier 1 - 4hr',
       'p1 - identity critical (24x7)', 'enterprise - 4 hour response',
       '24x7', 'businesscritical-4hr', '24x7 critical',
       's1 - critical infrastructure', 'internal-infrastructure-24x7',
       'tier 1 - 4 hour response', '24x7 critical infrastructure',
       '24x7 - infrastructure medium priority', 'sla-24x7',
       '24x7-support', 'internal sla - 4 hours',
       'internal infrastructure sla', 'sla-8x5', 'internal-default',
       'network - sla tier 2'], dtype=object)

In [24]:
def catergorise_sla(text):
  if 'gold' in text:
    return 'Gold'
  elif 'standard' in text or 'businesshours' in text or 'business hours' in text or 'business-hours' in text:
    return 'Standard'
  elif 'enterprise' in text or 'tier 1' in text or '24*7' in text or 'critical' in text :
    return 'enterprise 24/7'
  else:
    return 'Others'
df['sla_category']=df['sla_plan_clean'].apply(catergorise_sla)
df['sla_category'].value_counts()

sla_category
Standard           600
Gold                78
enterprise 24/7     36
Others              31
Name: count, dtype: int64